add_newline = false

[hostname]
ssh_only = false
format = "<[$hostname]($style)> "
trim_at = "-"
style = "bold dimmed white"
disabled = false

[time]
time_format = "%T"
#format = "🕙 $time($style) "
format = "$time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false

[package]
disabled = true
